- name: DevelopmentSetup
  hosts: localhost
  connection: local
  vars:
    # This variable gives us a boolean for deciding whether or not to become
    # root. It cascades down to any subsequent tasks unless overwritten.
    should_be_root:  "{{ true if ansible_pkg_mgr != 'brew' else false }}"
    newest_go_version: "$(curl https://go.dev/VERSION?m=text | head -n1)"

  tasks:
    - block:
      - name: Download atuin installer
        get_url: 
          url: https://github.com/atuinsh/atuin/releases/latest/download/atuin-installer.sh
          dest: ./atuin-installer.sh
        tags: 
          - atuin
      - name: Allow the atuin installer to execute
        shell: chmod +x atuin-installer.sh
        tags:
          - atuin
      - name: Execute the atuin installer
        shell: ./atuin-installer.sh
        tags:
          - atuin
      - name: Remove the atuin installer
        file: 
          path: ./atuin-installer.sh 
          state: absent
        tags:
          - atuin


      - name: awscli is present
        package:
          name: awscli
          state: present
      - name: bat is present
        package:
          name: bat
          state: present
      - name: btop is present
        package:
          name: btop
          state: present


      - name: check if cargo is installed
        shell: command -v cargo
        register: cargo_exists
        ignore_errors: yes
      - name: Cargo Download Installer
        when: cargo_exists is failed
        get_url:
          url: https://sh.rustup.rs
          dest: /tmp/sh.rustup.rs
          mode: '0755'
          force: 'yes'
        tags:
          - rust
      - name: install rust/cargo
        when: cargo_exists is failed
        shell: /tmp/sh.rustup.rs -y
        tags:
          - rust

      - name: fzf is present
        package:
          name: fzf
          state: present
      - name: gcc is present
        package:
          name: gcc
          state: present
      - name: gh is present
        package:
          name: gh
          state: present
      - name: set git user info
        shell: git config --global user.email "peteryurkovich1@gmail.com" && git config --global user.name "PeterYurkovich"
      - name: glab is present
        package:
          name: glab
          state: present


      - name: check if go is installed
        shell: command -v go
        register: go_exists
        ignore_errors: yes
      - name: Go Download Installer
        when: go_exists is failed
        shell: wget "https://dl.google.com/go/{{ newest_go_version }}.linux-amd64.tar.gz"
        tags:
          - go
      - name: extract go archive
        when: go_exists is failed
        shell: tar -C /usr/local -xzf "{{ newest_go_version }}.linux-amd64.tar.gz"
        tags:
          - go
      - name: remove go archive
        shell: rm -f "{{ newest_go_version }}.linux-amd64.tar.gz"
      - name: add local go folder
        shell: mkdir $HOME/go


      - name: helm is present
        package:
          name: helm
          state: present
      - name: jq is present
        package:
          name: jq
          state: present
      - name: allow lazygit install
        shell: dnf copr enable atim/lazygit -y
      - name: lazygit is present
        package:
          name: lazygit
          state: present
      - name: lsd is present
        package:
          name: lsd
          state: present
      - name: lua is present
        package:
          name: lua
          state: present
      # - name: Download nvm installer
      #   get_url: 
      #     url: https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.1/install.sh
      #     dest: ./nvm-installer.sh
      # - name: Allow the nvm installer to execute
      #   shell: chmod +x nvm-installer.sh
      # - name: Execute the nvm installer
      #   shell: ./nvm-installer.sh
      # - name: Remove the nvm installer
      #   file: 
      #     path: ./nvm-installer.sh 
      #     state: absent
      # - name: Install nvm
      #   ansible.builtin.shell: >
      #     curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.1/install.sh | bash
      - name: neovim is present
        package:
          name: neovim
          state: present
      - name: neovim plugins are present
        shell: nvim --headless "+Lazy! sync" +qa
      - name: ripgrep is present
        package:
          name: ripgrep
          state: present
      - name: stow is present
        package:
          name: stow
          state: present
      - name: tmux is present
        package:
          name: tmux
          state: present
      - name: unzip is present
        package:
          name: unzip
          state: present


    # - [x] atuin
    # - [x] awscli
    # - [x] btop
    # - [ ] colima (for docker backend on mac)
    # - [ ] docker (cli only)
    # - [ ] docker-compose
    # - [x] fzf
    # - [x] gcc
    # - [x] glab
    # - [ ] gnu-sed (mac only)
    # - [x] helm
    # - [x] jq
    # - [ ] kind
    # - [ ] kitty
    # - [ ] kubernetes-cli - https://stackoverflow.com/questions/60528766/how-to-install-kubectl-with-ansible
    # - [ ] kustomize
    # - [ ] lazygit - needs `sudo dnf copr enable atim/lazygit -y`
    # - [x] lsd
    # - [ ] luajit
    # - [ ] neovim
    # - [ ] nvim (plugins)
    # - [ ] nvm
    # - [ ] openshift-cli
    # - [ ] operator-sdk
    # - [ ] pipx (maybe)
    # - [ ] pixman (maybe)
    # - [ ] podman
    # - [ ] podman-compose
    # - [ ] pyenv
    # - [ ] python
    # - [ ] qemu (mac only)
    # - [x]] ripgrep
    # - [ ] starship
    # - [x] stow
    # - [x] tmux
    # - [ ] tree-sitter
    # - [ ] wget
    # - [ ] xonsh
    # - [ ] zoxide

    # run the scripts in the dotfiles repo
    # gitconfig update based on username of account? pyurkovi means redhat email while any other means peteryurkovich1@gmail.com
    # install python and ansible first?
