format = """
$hostname\
$os\
$shell\
$username\
$directory\
\
\
\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
\
\
\
$package\
$c\
$cmake\
$golang\
$nodejs\
$php\
$python\
$rust\
$fill\
\
\
\
$battery\
$cmd_duration
\
\
\
$character """





# Location Information
[hostname]
format = '[$ssh_symbol](bold blue)'

[os]
disabled = false

[shell]
disabled = false
style = 'cyan bold'

[username]
show_always = true
style_user = 'orange'
style_root = 'orange'
format = 'by [$user]($style) '

[directory]
style = 'purple'
format = ' in [$path]($style)[$read_only]($read_only_style) '
repo_root_format = ' in [$before_root_path]($before_repo_root_style)[$repo_root]($repo_root_style)[$path]($style)[$read_only]($read_only_style) '

[fill]
symbol = " "

# Right side of Command Line
[time]
disabled = false

[cmd_duration]
min_time = 0
show_milliseconds = true

# General Settings
[line_break]
disabled = true
