[colors]

# Normal
foreground       = '#ffffff'
background       = '#101010'
black            = '#101010'
blue             = '#f5a191'
cursor           = '#ffffff'
cyan             = '#ea83a5'
green            = '#90b99f'
magenta          = '#e29eca'
red              = '#f5a191'
white            = '#A0A0A0'
yellow           = '#e6b99d'

# Light colors
light-black      = '#7e7e7e'
light-blue       = '#b9aeda'
light-cyan       = '#f591b2'
light-green      = '#99ffe4'
light-magenta    = '#ecaad6'
light-red        = '#ff8080'
light-white      = '#ffffff'
light-yellow     = '#ffc799'
