apiVersion: logging.openshift.io/v1
kind: ClusterLogging
metadata:
  name: instance
  namespace: openshift-logging
  annotations:
    logging.openshift.io/preview-korrel8r-console: enabled
spec:
  managementState: Managed
  collection:
    type: vector
  logStore:
    type: lokistack
    lokistack:
      name: logging-loki
