apiVersion: apps/v1
kind: Deployment
metadata:
  name: bad-deployment
  namespace: openshift-monitoring
spec:
  selector:
    matchLabels:
      app: bad-deployment
  template:
    metadata:
      labels:
        app: bad-deployment
    spec:
      containers: 
      - name: bad-deployment
        image: quay.io/openshift-logging/vector:5.8
