apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: monitoring-edit-role-binding
  namespace: default
subjects:
- kind: User
  name: pyn
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: cluster-monitoring-edit
  apiGroup: rbac.authorization.k8s.io
